define([], function () {
    return {
        "DataSheetBackButton": "Back",
        "DataSheetConfirmButton": "Confirm",
        "DataSheetCancelButton": "Close",
        "DataSheetEditButton": "Edit",
        "DataSheetDeleteButton": "Delete",
        "DataSheetLabelCreatedOn": "Created on",
        "DataSheetLabelUpdatedOn": "Updated on",
        "DataSheetTabInfo": "Info",
        "DataSheetTabMarketReadiness": "Market Readiness",
        "DataSheetTabInfoMARequirements": "MA Requirements",
        "DataSheetSectionProperties": "Properties",
        "DataSheetSectionMarketItems": "Markets",
        "DataSheetSectionDocs": "Docs",
        "DataSheetSectionContacts": "Contacts",
        "DataSheetSectionLegalSvcProviders": "Legal Svc Providers",
        "DataSheetSectionAuthorities": "Authorities",
        "DataSheetSectionEutelsatEntities": "Eutelsat Entities",
        "DataSheetTabSNPs": "SNPs",

        "DataSheetItemDoesNotExist": "Item does not exist",
        "DataSheetNoDocumentSpace": "No documents available",
        "DataSheetNoRecordFound": "No record found",
        "DataSheetNoContacts": "No contacts available",
        "DataSheetDeleteModalTitle": "Delete Datasheet",
        "DataSheetDeleteModalMessage": "Are you sure you want to send this item to the site Recycle Bin?",

        //Country DataSheet
        "CountryDataSheetTitle": "COUNTRY",
        "CountryDataSheetInfoLabelIdentifier": "Identifier",
        "CountryDataSheetInfoLabelGrouping": "Grouping(s)",
        "CountryDataSheetInfoLabelSanctionCategory": "Sanction Category",
        "CountryDataSheetInfoLabelMaPriority": "MA Priorities",
        "CountryDataSheetInfoLabelIsSanctioned": "Is Sanctioned",
        "CountryDataSheetInfoLabelCapacity": "Capacity",
        "CountryDataSheetInfoLabelComments": "Comments",


        //Market DataSheet
        "MarketDataSheetTitle": "Market",
        "MarketDataSheetInfoLabelGrouping": "Grouping(s)",
        "MarketDataSheetInfoLabelCountry": "Country",

        "MarketDataSheetInfoLabelSanctionCategory": "Sanction Category",
        "MarketDataSheetInfoLabelMaPriority": "MA Priority(ies)",
        "MarketDataSheetInfoLabelIsSanctioned": "Is Sanctioned",
        "MarketDataSheetInfoLabelCapacity": "Capacity",
        "MarketDataSheetInfoLabelComments": "Comments",


        "MarketReadinessLabelEutelsatOwners": "Owner(s)",
        "MarketReadinessLabelAllVerticalRAGStatus": "Vertical RAG Status",
        "MarketReadinessLabelAllVerticalEstimatedDate": "Vertical Estimated Date",
        "MarketReadinessLabelAllVerticalEffectiveDate": "Vertical Effective Date",
        "MarketReadinessLabelAllVerticalComments": "Vertical Readiness Comments",

        "MarketReadinessLabelSpaceRAGStatus": "Space & NW RAG Status",
        "MarketReadinessLabelSpaceEstimatedDate": "Space & NW Estimated Date",
        "MarketReadinessLabelSpaceEffectiveDate": "Space & NW Effective Date",
        "MarketReadinessLabelSpaceComments": "Space & NW Readiness Comments",

        "MarketReadinessLabelLandFixedRAGStatus": "Land Fixed RAG Status",
        "MarketReadinessLabelLandFixedEstimatedDate": "Land Fixed Estimated Date",
        "MarketReadinessLabelLandFixedEffectiveDate": "Land Fixed Effective Date",
        "MarketReadinessLabelLandFixedComments": "Land Fixed Readiness Comments",

        "MarketReadinessLabelLandMobilityRAGStatus": "Land Mobility RAG Status",
        "MarketReadinessLabelLandMobilityEstimatedDate": "Land Mobility Estimated Date",
        "MarketReadinessLabelLandMobilityEffectiveDate": "Land Mobility Effective Date",
        "MarketReadinessLabelLandMobilityComments": "Land Mobility  Readiness Comments",

        "MarketReadinessLabelMaritimeRAGStatus": "Maritime RAG Status",
        "MarketReadinessLabelMaritimeEstimatedDate": "Maritime Estimated Date",
        "MarketReadinessLabelMaritimeEffectiveDate": "Maritime Effective Date",
        "MarketReadinessLabelMaritimeComments": "Maritime Readiness Comments",

        "MarketReadinessLabelAviationRAGStatus": "Aviation RAG Status",
        "MarketReadinessLabelAviationEstimatedDate": "Aviation Estimated Date",
        "MarketReadinessLabelAviationEffectiveDate": "Aviation Effective Date",
        "MarketReadinessLabelAviationComments": "Aviation Readiness Comments",
        "CountryDataSheetInfoLabelComments": "Comments",
        "MarketReadinessLabelResponsiblePartyItem": "Responsible(s)",

        "SnpReadinessLabelEutelsatOwners": "Owner(s)",
        "SnpReadinessLabelRAGStatus": "Vertical RAG Status",
        "SnpReadinessLabelEstimatedDate": "Vertical Estimated Date",
        "SnpReadinessLabelEffectiveDate": "Vertical Effective Date",
        "SnpReadinessLabelComments": "Vertical Readiness Comments",
        "SnpReadinessLabelNewButton": "New SNP Readiness Item",
        "SnpReadinessLabelEditButton": "Edit Item",
        "SnpReadinessLabelDeleteButton": "Delete Item",
        "SnpReadinessLabelResponsiblePartyItem": "Responsible(s)",

        NolDataSheetTitle: "NOL",
        NolDataSheetEditFormTitle: "Edit NOL",
        NolDataSheetInfoLabelAuthority: "Authority",
        NolDataSheetInfoLabelSummary: "Summary",
        NolDataSheetInfoLabelComments: "Comments",
        NolDataSheetInfoLabelType: "Content Type",
        NolDataSheetInfoLabelMarkets: "Markets",
        NolDataSheetInfoLabelEutelsatOwner: "Owners",
        NolDataSheetInfoLabelRequestedPartyItem: "Authority",
        NolDataSheetInfoLabelRequestedPartyContacts: "Authority Contact(s)",
        NolDataSheetInfoLabelResponsiblePartyContacts: "Holder Contact(s)",
        NolDataSheetInfoLabelRequestedPartyType: "Authority Type",
        NolDataSheetInfoLabelRequirementType: "Requirement Type",
        NolDataSheetInfoLabelSnps: "Snp(s)",
        NolDataSheetInfoLabelRagStatus: "RAG Status",
        NolDataSheetInfoLabelSynthesis: "Synthesis Status",
        NolDataSheetInfoLabelMaVertical: "Verticals",
        NolDataSheetInfoLabelGeoLeo: "GEO/LEO",
        NolDataSheetInfoLabelApplicationDate: "Application Date",
        NolDataSheetInfoLabelEstimatedDate: "Estimated Date",
        NolDataSheetInfoLabelEffectiveDate: "Effective Date",
        NolDataSheetInfoLabelResponsiblePartyItem: "Holder",
        NolDataSheetInfoLabelResponsibleParty: "Holder Type",
        NolDataSheetInfoLabelLetter1SentDate: "Letter1 Sent Date",
        NolDataSheetInfoLabelLetter2SentDate: "Letter2 Sent Date",
        NolDataSheetInfoLabelLetter1Milestone: "Letter1 Milestone",
        NolDataSheetInfoLabelLetter2Milestone: "Letter2 Milestone",
        NolDataSheetInfoLabelResponseDate: "Response Date",
        NolDataSheetInfoLabelResponseSummary: "Response Summary",


        //MA Genric
        "MAGenricRequirementDataSheetEditFormTitle": "Edit MA Generic",
        "MAGenricRequirementDataSheetTitle": "MA Requirement Generic",


        //MA Generic
        MAGenericRequirementDataSheetInfoLabelAuthority: "Authority",
        MAGenericRequirementDataSheetInfoLabelSummary: "Summary",
        MAGenericRequirementDataSheetInfoLabelComments: "Comments",
        MAGenericRequirementDataSheetInfoLabelType: "Content Type",
        MAGenericRequirementDataSheetInfoLabelMarkets: "Market(s)",
        MAGenericRequirementDataSheetInfoLabelEutelsatOwner: "Owners",
        MAGenericRequirementDataSheetInfoLabelRequestedPartyItem: "Authority",
        MAGenericRequirementDataSheetInfoLabelRequestedPartyContacts: "Authority Contact(s)",
        MAGenericRequirementDataSheetInfoLabelRagStatus: "RAG Status",
        MAGenericRequirementDataSheetInfoLabelSynthesis: "Synthesis Status",
        MAGenericRequirementDataSheetInfoLabelMaVertical: "Verticals",
        MAGenericRequirementDataSheetInfoLabelGeoLeo: "GEO/LEO",
        MAGenericRequirementDataSheetInfoLabelApplicationDate: "Application Date",
        MAGenericRequirementDataSheetInfoLabelEstimatedDate: "Estimated Date",
        MAGenericRequirementDataSheetInfoLabelEffectiveDate: "Effective Date",
        MAGenericRequirementDataSheetInfoLabelResponsiblePartyItem: "Holder",
        MAGenericRequirementDataSheetInfoLabelResponsibleParty: "Holder Type",
        MAGenericRequirementDataSheetInfoLabelReletedItems: 'Releted Items',
        MAGenericRequirementDataSheetInfoLabelResponsiblePartyContacts: "Holder Contact(s)",
        MAGenericRequirementDataSheetInfoLabelRequirementType: "Requirement Type",
        MAGenericRequirementDataSheetInfoLabelSnps: "Snp(s)",


        FormMARequirementTypeDistributionPartner: "Distribution Partner",
        FormMARequirementTypeSNP: "SNP",
        FormMARequirementGenericTypeOrganization: "Organization",
        FormMARequirementGenericTypeRegulator: "Regulator",
        FormMARequirementGenericTypeAdministration: "Administration",
        FormMARequirementTypeTeleportPartner: "Teleport Partner",
        FormMARequirementGenericTypeLawFirm: "Law Firm",
        FormMARequirementGenericTypeLegalRepresentative: "Legal Representative",

        //Legal Requirement
        LegalRequirementDataSheetTitle: "Legal Requirement",
        LegalRequirementDataSheetInfoLabelAuthority: "Authority",
        LegalRequirementDataSheetInfoLabelSummary: "Summary",
        LegalRequirementDataSheetInfoLabelComments: "Comments",
        LegalRequirementDataSheetInfoLabelType: "Content Type",
        LegalRequirementDataSheetInfoLabelMarkets: "Markets",
        LegalRequirementDataSheetInfoLabelEutelsatOwner: "Owners",
        LegalRequirementDataSheetInfoLabelRequestedPartyType: "Authority Type",
        LegalRequirementDataSheetInfoLabelRequestedPartyItem: "Authority",
        LegalRequirementDataSheetInfoLabelRequestedPartyContacts: "Authority Contact(s)",
        LegalRequirementDataSheetInfoLabelRagStatus: "RAG Status",
        LegalRequirementDataSheetInfoLabelSynthesis: "Synthesis Status",
        LegalRequirementDataSheetInfoLabelMaVertical: "Verticals",
        LegalRequirementDataSheetInfoLabelGeoLeo: "GEO/LEO",
        LegalRequirementDataSheetInfoLabelApplicationDate: "Application Date",
        LegalRequirementDataSheetInfoLabelEstimatedDate: "Estimated Date",
        LegalRequirementDataSheetInfoLabelEffectiveDate: "Effective Date",
        LegalRequirementDataSheetInfoLabelResponsiblePartyItem: "Holder",
        LegalRequirementDataSheetInfoLabelResponsibleParty: "Holder Type",
        LegalRequirementDataSheetInfoLabelResponsiblePartyContacts: "Holder Contact(s)",
        LegalRequirementDataSheetInfoLabelRequirementType: "Requirement Type",
        LegalRequirementDataSheetInfoLabelSnps: "Snp(s)",

        //MA License
        "MALicenseRequirementDataSheetTitle": "MALicense Requirement",
        "MALicenseRequirementDataSheetInfoLabelAuthority": "Authority",
        "MALicenseRequirementDataSheetInfoLabelSummary": "Summary",
        "MALicenseRequirementDataSheetInfoLabelComments": "Comments",
        "MALicenseRequirementDataSheetInfoLabelType": "Content Type",
        "MALicenseRequirementDataSheetInfoLabelTrialDemo": "Demo/Trial",
        "MALicenseRequirementDataSheetInfoLabelReference": "Reference",
        "MALicenseRequirementDataSheetInfoLabelMarkets": "Market(s)",
        "MALicenseRequirementDataSheetInfoLabelEutelsatOwner": "Owners",
        //"MALicenseRequirementDataSheetInfoLabelRequestedPartyItem": "Requested Party",
        "MALicenseRequirementDataSheetInfoLabelRequestedPartyItem": "Authority",
        "MALicenseRequirementDataSheetInfoLabelRequestedPartyType": "Authority Type",
        "MALicenseRequirementDataSheetInfoLabelRequestedPartyContacts": "Authority Contact(s)",
        "MALicenseRequirementDataSheetInfoLabelRagStatus": "RAG Status",
        "MALicenseRequirementDataSheetInfoLabelSynthesis": "Synthesis Status",
        "MALicenseRequirementDataSheetInfoLabelMaVertical": "Verticals",
        "MALicenseRequirementDataSheetInfoLabelGeoLeo": "GEO/LEO",
        "MALicenseRequirementDataSheetInfoLabelApplicationDate": "Application Date",
        "MALicenseRequirementDataSheetInfoLabelEstimatedDate": "Estimated Date",
        "MALicenseRequirementDataSheetInfoLabelEffectiveDate": "Effective Date",
        "MALicenseRequirementDataSheetInfoLabelExpirationDate": "Expiration Date",
        "MALicenseRequirementDataSheetInfoLabelResponsiblePartyItem": "Holder",
        "MALicenseRequirementDataSheetInfoLabelRequirementType": "Requirement Type",
        "MALicenseRequirementDataSheetInfoLabelResponsibleParty": "Holder Type",
        "MALicenseRequirementDataSheetInfoLabelResponsiblePartyContacts": "Holder Contact(s)",
        "MALicenseRequirementDataSheetInfoLabelReletedItems": 'Releted Items',
        "MALicenseRequirementDataSheetInfoLabelFrequency": 'Renewal Term',
        "MALicenseRequirementDataSheetTitle": "MA Requirement License",
        "MALicenseRequirementDataSheetEditFormTitle": "Edit MA License",
        "MALicenseRequirementDataSheetInfoLabelSnps": "SNP(s)",


        // SNP DataSheet
        "SNPDataSheetTitle": "SNP",
        "SNPDataSheetInfoLabelCountry": "Country",
        "SNPDataSheetInfoLabelStatus": "Status",
        "SNPDataSheetInfoLabelCity": "City",
        "SNPDataSheetInfoLabelTeleportPartner": "Teleport Partner",
        "SNPDataSheetInfoLabelComments": "Comments",
        "SNPDataSheetInfoLabelSummary": "Summary",
        "SNPDataSheetEditFormTitle": "Edit SNP",
        "SNPDataSheetInfoLabelContentType": "Content Type",
        "SNPDataSheetInfoLabelEutEntity": "Eutelsat Entity",
        "SNPDataSheetInfoLabelTeleportPartner": "Teleport Partner",


        // Eutelsat Entity
        "EutelsatEntityDataSheetTitle": "Eutelsat Entity",
        "EutelsatEntityDataSheetEditFormTitle": "Edit Eutelsat Entity",
        "EutelsatEntityDataSheetInfoLabelName": "Name",
        "EutelsatEntityDataSheetInfoLabelAddress": "Legal Address",
        "EutelsatEntityDataSheetInfoLabelStatus": "Status",
        "EutelsatEntityDataSheetInfoLabelCountry": "Country",
        "EutelsatEntityDataSheetInfoLabelSummary": "Summary",
        "EutelsatEntityDataSheetInfoLabelComments": "Comments",


        //TP Labels
        "TPDataSheetTitle": "TP",
        "TPDataSheetEditFormTitle": "Edit TP",
        "TPDataSheetInfoLabelName": "Name",
        "TPDataSheetInfoLabelMarkets": "Market(s)",
        "TPDataSheetInfoLabelPortal": "Portal",
        "TPDataSheetInfoLabelStatus": "Status",
        "TPDataSheetInfoLabelComments": "Comments",
        "TPDataSheetInfoLabelAddress": "Legal Address",
        "TPDataSheetInfoLabelOwners": "Owners",
        "TPDataSheetInfoLabelSummary": "Summary",

        "AuthorityDataSheetEditFormTitle": "Edit Authority",
        "AuthorityDataSheetInfoLabelSummary": "Summary",
        "AuthorityDataSheetInfoLabelAddress": "Legal address",
        "AuthorityDataSheetInfoLabelGrouping": "Grouping(s)",
        "AuthorityDataSheetInfoLabelCountries": "Country(ies)",
        "AuthorityDataSheetInfoLabelPortal": "Portal",
        "AuthorityDataSheetInfoLabelOwners": "Owners",
        "AuthorityDataSheetInfoLabelComments": "Comments",

        //LegalSvcProvider Datasheet
        "LegalSvcProviderDataSheetTitle": "Law Firm",
        "LegalSvcProviderDataSheetSummary": "Summary",
        "LegalSvcProviderDataSheetAddress": "Legal Address",
        "LegalSvcProviderDataSheetCountries": "Country(ies)",
        "LegalSvcProviderDataSheetStatus": "Status",
        "LegalSvcProviderDataSheetOwners": "Owners",
        "LegalSvcProviderDataSheetComments": "Comments",
        "DataSheetNoContacts": "No record found",
        "LegalSvcProviderDatasheetTypeLegalRep": "Legal Representative",
        "LegalSvcProviderDatasheetEditLawFirm": "Edit Law Firm",

        //DP Datasheet
        "DPDataSheetTitle": "Distribution Partner",
        "DPDataSheetInfoLabelSummary": "Summary",
        "DPDataSheetInfoLabelAddress": "Legal Address",
        "DPDataSheetInfoLabelPortal": "Portal",
        "DPDataSheetInfoLabelStatus": "Status",
        "DPDataSheetInfoLabelOwners": "Owners",
        "DPDataSheetInfoLabelComments": "Comments",
        "DPDataSheetEditFormTitle": "Edit Distribution Partner",
        "DPDatasheetTypeDistributionPartner": "Distribution Partner",


        //Payment Datasheet
        "PaymentDataSheetSummary": "Summary",
        "PaymentDataSheetFees": "Fees",
        "PaymentDataSheetStatus": "Status",
        "PaymentDataSheetDueDate": "Due Date",
        "PaymentDataSheetDatePaid": "Date Paid",
        "PaymentDataSheetBeneficiary": "Payment Recipient Type",
        "PaymentDataSheetBeneficiaryItem": "Payment Recipient",
        "PaymentDataSheetContacts": "Payment Recipient Contact(s)",
        "PaymentDataSheetVatFree": "Vat Free",
        "PaymentDataSheetVat": "Vat",
        "PaymentDataSheetComments": "Comments",
        "PaymentDataSheetVatFreeCost": "Vat Free",
        "PaymentDataSheetEditFormTitle": "Edit Payment",

        //Fee Datasheet
        "FeeDataSheetSummary": "Summary",
        "FeeDataSheetCategory": "Category",
        "FeeDataSheetItem": "Related To",
        "FeeDataSheetStatus": "Status",
        "FeeDataSheetFrequency": "Frequency",
        "FeeDataSheetDueDate": "Due Date",
        "FeeDataSheetChargedBy": "Fee Issuer Type",
        "FeeDataSheetChargeByItem": "Fee Issuer",
        "FeeDataSheetVatFreeCost": "Vat Free",
        "FeeDataSheetVatRate": "Vat Rate",
        "FeeDataSheetVat": "Vat",
        "FeeDataSheetCostType": "Cost Type",
        "FeeDataSheetPoNonPO": "Po/Non PO",
        "FeeDataSheetComments": "Comments",
        "FeeDataSheeteditFormTitle": "Edit Fee",
        "NewFeeButtonLabel": "New Fee",

        // contact datasheet
        ContactDataSheetTitle: "Contact",
        ContactDataSheetEditFormTitle: "Edit Contact",
        ContactDataSheetInfoLabelFirstName: "First Name",
        ContactDataSheetInfoLabelLastName: "Last Name",
        ContactDataSheetInfoLabelEmail: "Email",
        ContactDataSheetInfoLabelPhoneNumber: "Phone Number",
        ContactDataSheetInfoLabelItem: "Related To",
        ContactDataSheetInfoLabelEutelsatContact: "Eutelsat Contact",
        ContactDataSheetInfoLabelDepartment: "Department",
        ContactDataSheetInfoLabelSummary: "Summary",
        ContactDataSheetInfoLabelComments: "Comments",
        ContactDataSheetInfoLabelJobTitle: "Job Title",
        ContactDataSheetNewContact: "New Contact",


        //Payment view
        "PaymentLabelNewButton": "New Payment Item",
        //Country Readiness View
        MarketReadinessLabelNewButton: "New Country Readiness Item",
        LibraryViewRecycleBinConfirmation: "Are you sure you want to send this item to the site Recycle Bin?",

        //Form
        FormAccessDeniedMessage: "You don't have permission on this Datasheet",

        //Delete Message
        DeleteSuccessMessage: "The datasheet item has been deleted successfully.",
        DeleteErrorMessage: "An error occurred while deleting the datasheet item.",

    }
});